# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Youri-Package-RPM-Builder
version:      0.1.2
version_from: lib/Youri/Package/RPM/Builder.pm
installdirs:  site
requires:
    RPM4:                          0
    String::ShellQuote:            0
    Test::Exception:               0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
